### ISSUE TITLE
xsltproc file size > 100kb

### ISSUE THREAD

**Issue by solinad21** [ilyar/xsltproc#8]
with files > 100 kb i get truncated responses, 
I think they are async problems

**Comment by solinad21** [comment]
how do i get async functionality?

**Comment by ilyar** [comment]
@solinad21 please give an example of your steps and data, it will help to find solutions

**Comment by solinad21** [comment]
[ver4dot0.zip](https://github.com/ilyar/xsltproc/files/11183822/ver4dot0.zip)


this is my script:

`...
...
...
return new Promise((resolve, reject) => {
    var xsltproc = require('xsltproc')
    var xslt = xsltproc.transform(pathXslt, pathXml);
    xslt.stdout.on('data', function (data) {
       resolve(data.toString());        
    })
});
...
...
...
`

**Comment by ilyar** [comment]
@solinad21 try it
```javascript
const xsltproc = require('xsltproc');

function transform(pathXslt, pathXml) {
  return new Promise((resolve, reject) => {
    const xslt = xsltproc.transform(pathXslt, pathXml);
    const content = [];
    xslt.stdout.on('data', function (data) {
      content.push(data);
    });
    xslt.stderr.on('data', function (data) {
      reject(data.toString());
    });
    xslt.on('exit', function () {
      resolve(Buffer.concat(content).toString());
    });
  });
}

transform(
  'path.xsl',
  'path.xml'
)
  .then(console.log)
  .catch(console.error);
```
tested on data size 220Kb

**Comment by solinad21** [comment]
thanks, work ok.
